[package]
name = "genossi_service_impl"
version.workspace = true
edition.workspace = true

[features]
default = ["mock_auth"]
mock_auth = ["genossi_service/mock_auth"]
oidc = ["genossi_service/oidc"]

[dependencies]
genossi_dao = { path = "../genossi_dao" }
genossi_service = { path = "../genossi_service" }
genossi_config = { path = "../genossi_config" }
genossi_mail = { path = "../genossi_mail" }
async-trait = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
calamine = { workspace = true }
typst = { workspace = true }
typst-pdf = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
sha2 = "0.10"
qrcode = { workspace = true }
rand = { workspace = true }
path-clean = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
flate2 = "1"
tar = "0.4"
x509-tsp = "0.1.0"
cmpv2 = "0.2.0"
der = { version = "0.7", features = ["alloc", "derive", "oid"] }
cms = { version = "0.2.3", features = ["alloc"] }
const-oid = { version = "0.9", features = ["db"] }
csv = { workspace = true }
rust_xlsxwriter = { workspace = true }
spki = "0.7"

[dev-dependencies]
tempfile = "3"
hex-literal = "0.4"
mockall = { workspace = true }
[lints]
workspace = true
