[application]

# App (Project) Name
name = "inventurly-frontend"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Inventurly"

# Disable wasm-opt optimization to avoid parsing errors
base_path = ""

[web.wasm-opt.debug]
# Disable wasm-opt optimization
optimizations = false
skip = true

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["/tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[[web.proxy]]
backend = "http://localhost:3000/products"
[[web.proxy]]
backend = "http://localhost:3000/containers"
[[web.proxy]]
backend = "http://localhost:3000/auth"
[[web.proxy]]
backend = "http://localhost:3000/duplicate-detection"
[[web.proxy]]
backend = "http://localhost:3000/csv-import"
[[web.proxy]]
backend = "http://localhost:3000/permission"
[[web.proxy]]
backend = "http://localhost:3000/racks"
[[web.proxy]]
backend = "http://localhost:3000/product-racks"
[[web.proxy]]
backend = "http://localhost:3000/inventur"
[[web.proxy]]
backend = "http://localhost:3000/inventur-measurement"
[[web.proxy]]
backend = "http://localhost:3000/swagger-ui"
